### ISSUE TITLE
 Update complete, Update faild at the same time when there is no internet connection

### ISSUE THREAD

**Issue by pypygeek** [hanul93/kicomav#10]
Hi.

Update complete, Update faild at the same time when there is no internet connection

I always use kicom antivirus well.

Thank you

![update](https://user-images.githubusercontent.com/19469996/69518577-475f5900-0f9b-11ea-9e0c-b5e3d1ecbbd6.PNG)

**Comment by hanul93** [comment]
Thank you for reporting the error.

버그를 알려주셔서 감사합니다

**Comment by pypygeek** [comment]
The update completion message appears, but as the file is deleted, a failure message also appears.

![20210305_165442](https://user-images.githubusercontent.com/19469996/110084993-e9dbce00-7dd3-11eb-8e01-463bee8a64d7.png)

Currently being detected by the following antivirus companies. (2021-03-05 07:59:04 UTC)
- SecureAge APEX
- Cylance
- FireEye
- Kaspersky
- Malwarebytes
- Qihoo-360
- Tencent
- Yandex
- Zillya
- ZoneAlarm by Check Point
- Windows Defender

I'll report it to windows defender in false positives.
