### ISSUE TITLE
ubuntu 18.04 "I/O errors "

### ISSUE THREAD

**Issue by senioi** [hanul93/kicomav#12]
How to solve this?

**Comment by hanul93** [comment]
Can you show me a screenshot of the error?

**Comment by senioi** [comment]
@hanul93 thanks for your reply.
I try to scan a sample directory.But show "I/O errors"
![20191204054627](https://user-images.githubusercontent.com/42415346/70092586-98d1ad00-1659-11ea-9ced-1692349d7709.png)

**Comment by senioi** [comment]
like this sample 

[F2E867D0283CC063C29281326A0AC540D2A705696635AE91C14FE2B610549B75.zip](https://github.com/hanul93/kicomav/files/3918858/F2E867D0283CC063C29281326A0AC540D2A705696635AE91C14FE2B610549B75.zip)

**Comment by rremo** [comment]
TrID/32 - File Identifier v2.24 - (C) 2003-16 By M.Pontello
Definitions found:  12117
Analyzing...
Collecting data from file: CCD6B478D1FAF472510A6B87C553838C59285356AAC36E608C57087495A46275.email
 50.1% (.) ELF Executable and Linkable format (Linux) (4025/14)
 49.8% (.O) ELF Executable and Linkable format (generic) (4000/1)

**Comment by hanul93** [comment]
I have confirmed the error you gave me.
This error is a problem in parsing ELF 64bit files.
I will fix this error.

**Comment by hanul93** [comment]
Fixed it https://github.com/hanul93/kicomav/commit/72e15b38620a3abe1e2b2151b47255c481409d0f .
I will update it soon.

**Comment by senioi** [comment]
@hanul93 kicomav support decompression to save samples, most samples may need to be analyzed manually using IDA

**Comment by hanul93** [comment]
@senioi Yes, KicomAV support decompression to save samples.
But you must run developer mode and using option --sigtool.
