### ISSUE TITLE
Benefit from Armadito av?

### ISSUE THREAD

**Issue by WPFilmmaker** [hanul93/kicomav#14]
First of all thanks for developing kicomav, opensource antivirus are a rare thing...

I am opening this ticket to suggest collaborating/benefitting from Armaditoav. About Armaditoav from the official site: "Armadito Antivirus is an antivirus that protects your computers and servers from malware and viruses.

Armadito includes classical signature-based malware detection and provides innovative heuristic detection modules for binaries (MS-Windows and GNU/Linux) and for PDF documents.

An intuitive and user-friendly interface gives access to all Armadito’s features: on-demand scanning, real-time protection, quarantine zone, threat detection journal…

Armadito is remotely manageable for enterprises and organisations using a central administration console."

Here is the project page: https://github.com/armadito/armadito-av

AFAIK it is just a gui of the antivirus, as it uses claimav for its cleaning. As end of 2019 Armadito seems stalled/dead, but maybe you could use to improve kicomav?

You have the engine, Armadito could give you the gui and you could get an opensource antivirus and alternative to clamav:)

**Comment by hanul93** [comment]
Hello @WPFilmmaker 
Thank you for your suggestion.

As you know KicomAV does not have a gui. So your suggestion is so good for KicomAV.

Please let me know your opinion about next steps.
And Happy New Year!

**Comment by WPFilmmaker** [comment]
@hanul93 Thank you for your interests and happy belated new year!

I am not a developer but I noticed that several users have interest (looking at the tickets on armadito's github) in the antivirus but the project seems inactive.

What you could try to do is contact the original developers and ask if they are interested in joint development otherwise you can just reuse their GUI's if licenses are good.

A clamav alternative is much needed, and I think a GUI would really help the adoption of your antivirus.

I would also recommend to try applying to Google Summer of Code, you would be surprised by how many potential students are interested in working during the summer! I proposed the same to Synfigstudio (a 2d animation tool) and for several months the ticket was empty but then it managed to attract several students and eventually the project got 2 paid students to improve the software.

I opened a ticket on Armadito's page so users who go there can find your project as well.

**Comment by hanul93** [comment]
@WPFilmmaker Thank you for your suggestion.  I will contact the developer.  Also thank you for the good information.

**Comment by WPFilmmaker** [comment]
@hanul93 any news?

**Comment by hanul93** [comment]
@WPFilmmaker Not yet.
