### ISSUE TITLE
How to know I/O Error File?

### ISSUE THREAD

**Issue by pypygeek** [hanul93/kicomav#15]
Hi,
I can't see all the results by scrolling.
How to know I/O Error File?

![IO_ERROR](https://user-images.githubusercontent.com/19469996/73625314-a02c2b80-4687-11ea-9f55-dba7b2f86a3f.PNG)

OS: Windows 10 Pro 64Bit
Python Version :  2.7.14
Kicom Engine Version : 0.32
DB : Last Upodated Sun May 26 02:43:40 2019 UTC Signature number: 2,375

How to Run Kicom? -> C:\kicom\Release > python k2.py C:\ -r -I

How can I participate in finding Kicom I/O errors?

안녕하세요.
C:\ 검사시 453개 파일에 대하여 I/O Error가 발생하는데 해당 파일을 수집하여 Kicom 엔진 개선에 참여하고 싶습니다.

검사된 명령 프롬프트에 스크롤을 올리면 전체 검사한 파일들이 나오는 것이 아닌 검사 종료까지에 일부 몇 십개에 파일결과만 알 수 있어서 오류가 발생한 파일을 찾기가 힘듭니다.

이 에러를 찾아 리포팅할 수 있는 방법을 알려주실 수 있을까요?

**Comment by pypygeek** [comment]
Some have been fixed in administrator mode.
일부는 명령 프로프트 관리자모드로 에러가 해결되었습니다.
 
![Uploading kicom_adminScan.PNG…]()

**Comment by hanul93** [comment]
현재 키콤백신 코드로는 I/O Error가 발생한 파일을 알 수가 없습니다.

k2engine.py 소스코드 내부 __scan_file 함수 내부에 self.result['IO_errors'] += 1 코드가 존재합니다.
여기에 print filename 을 하면 I/O Error 파일을 확인할 수 있습니다.
