### ISSUE TITLE
Folders and files not scanned when folder name contains []

### ISSUE THREAD

**Issue by pypygeek** [hanul93/kicomav#16]
Hi,
I found Folders and files not scanned when folder name contains []

![io](https://user-images.githubusercontent.com/19469996/76181466-8771e100-6204-11ea-8c69-a9ded34bcf60.PNG)

OS: Windows 10 Pro 64Bit
Python Version : 2.7.13
Kicom Engine Version : 0.32
DB : Last Upodated Sun May 26 02:43:40 2019 UTC Signature number: 2,375

How to Run Kicom? -> C:\kicom\Release > python k2.py PATH\\[test]plpbt-5.0.15 -f

**Comment by hanul93** [comment]
Thanks you.

**Comment by hanul93** [comment]
This bug is due to the nature of glob.glob.
I will fix this bug by referencing the following URL.

https://stackoverflow.com/questions/2595119/python-glob-and-bracket-characters
