### ISSUE TITLE
Kicomav run

### ISSUE THREAD

**Issue by eymentahamidilli** [hanul93/kicomav#18]
Don't have a downloader for that?
If not, which file should I run from?

**Comment by rremo** [comment]
See under https://github.com/hanul93/kicomav#quick-start - Quick start

**Three quick start options are available:**
- [Download the latest release](https://github.com/hanul93/kicomav/archive/master.zip) and unzip it.
- Clone the repo: git clone git://github.com/hanul93/kicomav.git
- Build KicomAV Engine & Plugins modules : build.sh build or build.bat build
- You can see Release Directory. Change the Release directory and run k2.py.

**Comment by eymentahamidilli** [comment]
So from which file should I open

**Comment by pypygeek** [comment]
**Usage**
C:\kicomav\Release> python k2.py [path] [options]
Example 1 : KicomAV help Options

C:\kicomav\Release> python k2.py
KicomAV_Run

Example 2 : Update for malware signatures

C:\kicomav\Release> python k2.py --update
KicomAV_Update

Example 3 : Scan for current path

C:\kicomav\Release> python k2.py . -I
KicomAV_Scan

Example 4 : Scan for ZIP files

C:\kicomav\Release> python k2.py sample -r -I
KicomAV_Scan_Zip

Example 5 : Display Virus list

C:\kicomav\Release> python k2.py -V
KicomAV_Virus_list

**Comment by pypygeek** [comment]
This video will help you.
[https://youtu.be/32M6QKboCGM](url)

**Comment by eymentahamidilli** [comment]
It must be inside the C: disk, isn't it dangerous for the computer?

**Comment by pypygeek** [comment]
I understood it as saying that kicom antivirus might be able to execute malicious code while scanning, but is it correct that I understand your talk?

**Comment by eymentahamidilli** [comment]
> Bunu, kicom antivirüsün tarama sırasında kötü amaçlı kod yürütebileceğini söylüyormuş gibi anladım, ancak konuşmanızı anladığım doğru mu?

No, because the C: disk is the master disk, it can corrupt system files because the C: disk contains Windows files.

**Comment by pypygeek** [comment]
viruses cure and malware are deleted, so it isn't that system files will be damaged.
kicom antivirus checks the whitelist before applying the DB.
Nevertheless, if you find false positive files detected by kicom antivirus, please let kicom antivirus know.
So, you can use it with C: disk as well.

**Comment by hanul93** [comment]
@pypygeek Thank you for responding on my behalf.
