### ISSUE TITLE
False report

### ISSUE THREAD

**Issue by pypygeek** [hanul93/kicomav#19]
Hi!
The deletion is marked as complete, but the deletion has not been completed.

**[SHA-256]**

- 5EE3960DAB3F584E50078CC9D14C21B24D58FF4D826A189CFB386C76703C6844

- 6CCF2E1EBFB0325E0578213F108326CD3AFE2104CF917A42310C94743E1FED3A

![20210226_153447](https://user-images.githubusercontent.com/19469996/109264495-6c9ae100-7848-11eb-9057-d06e3d6fe48b.png)

**Comment by hanul93** [comment]
Please use kicomav v0.33 version.

![image](https://user-images.githubusercontent.com/4372914/109781508-52e40a00-7c4b-11eb-9528-5e9fb0e7c5ae.png)
![image](https://user-images.githubusercontent.com/4372914/109781561-6000f900-7c4b-11eb-8778-8cd58562568e.png)
