### ISSUE TITLE
test-build 실행 시 오류

### ISSUE THREAD

**Issue by chohb** [hanul93/kicomav#2]
< Error Contents Start > 

Engine\plugins\alz.py
Engine\plugins\apk.py
Engine\plugins\attach.py
Engine\plugins\base1.py
Engine\plugins\coff.py
Engine\plugins\dummy.py
Engine\plugins\egg.py
Engine\plugins\eicar.py
Engine\plugins\emalware.py
Engine\plugins\embeded.py
Engine\plugins\hwp.py
Engine\plugins\kavutil.py
Engine\plugins\kernel.py
Engine\plugins\kicom.lst
Engine\plugins\macro.py
Engine\plugins\ole.py
Engine\plugins\olenative.py
Engine\plugins\pdf.py
Engine\plugins\pefile.py
Engine\plugins\pyz.py
Engine\plugins\script.py
Engine\plugins\upx.py
Engine\plugins\zip.py
       23개 파일이 복사되었습니다.
        1개 파일이 복사되었습니다.
Sample\dummy.alz
Sample\dummy.egg
Sample\dummy.txt
Sample\test.egg
Sample\test.zip
        5개 파일이 복사되었습니다.
......
IOError: [Errno 2] No such file or directory: 'key.skr'
Traceback (most recent call last):
  File "kmake.py", line 144, in <module>
    fp = open('key.skr', 'rt') # 개인키
IOError: [Errno 2] No such file or directory: 'key.skr'
D:\Install Files\악성코드분석\kicomav-master\Release\plugins\*.pyc을(를) 찾을 수 없습니다.
        1개 파일이 복사되었습니다.
..\Test\test_dummy_cure.py
        1개 파일이 복사되었습니다.
E
======================================================================
ERROR: test_dummy_cure (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_dummy_cure
Traceback (most recent call last):
  File "c:\python27\lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "c:\python27\lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "D:\Install Files\악성코드분석\kicomav-master\Release\test_dummy_cure.py", line 7, in <module>
    import kavcore
ImportError: No module named kavcore

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)

< Error Contents End > 

참고 자료
D:\Install Files\악성코드분석\kicomav-master\Release>python -V
Python 2.7.12

**Comment by hanul93** [comment]
This issue was cleared in version 0.27.
