### ISSUE TITLE
zlib.error: Error -3 while decomparessing data: incorrect header check

### ISSUE THREAD

**Issue by researcherGeekLab** [hanul93/kicomav#4]
![20170930_172645](https://user-images.githubusercontent.com/19469996/31044161-106dc2ee-a605-11e7-8321-1f1b51bc88f2.png)

실행은 잘 되지만 검사할 경로를 주게 되면 위와 같은 오류가 납니다.

**Comment by hanul93** [comment]
0.29 브렌치 소스를 사용하고 계신가요?
그렇다면 --update 옵션을 사용해서 시그너처를 다운로드 받아서 사용하실 수 없습니다.
KicomAV 0.28 버전의 악성코드 시그너처는 0.29 버전 부터는 호화되지 않습니다.
---------------------------------------------------------------------------
Are you using a 0.29 branch sauce?
If so, you can not use malware signatures by download option(--update).
KicomAV 0.28 malware signatures are not compatible from 0.29.

**Comment by researcherGeekLab** [comment]
그렇다면 --update가 아닌 최신DB로 업데이트 할 수 있는 옵션이 있나요?

**Comment by hanul93** [comment]
0.29 버전부터 개발자 버전과 최종 릴리즈 버전의 업데이트를 구분해서 악성코드 DB를 제공하도록 하겠습니다.

I will provide separate malware signatures for developers version and releases version from KicomAV v0.29.

**Comment by researcherGeekLab** [comment]
앗! 번거로우실 텐데 감사합니다.
