### ISSUE TITLE
Python 3.5 이상 지원

### ISSUE THREAD

**Issue by jaepil** [hanul93/kicomav#6]
Python 2.7은 버그 수정, 보안 패치 외에는 개발이 중단된 상태이고, 이마저도 2020년에 완전 중단될 예정입니다.
따라서 2.7과의 하위 호환성을 유지하면서 3.5 이상에서 문제 없이 동작하도록 수정을 제안합니다.

six, future 패키지 사용과 몇 가지 가이드라인을 지키면 쉽게 달성 가능한 목표이며, 최근 프로젝트들이 Python 3.x로 많이 옮겨가는 추세이기 때문에 의미 있는 작업이 될 거라 생각합니다.

Python 2.7, 3.5, 3.6 동시 지원이 괜찮다 생각하시면 제가 작업해보도록 하겠습니다.

관련 자료: http://python-future.org/

**Comment by hanul93** [comment]
말씀하신대로 파이썬 2.7, 3.5, 3.6이 동시에 지원된다면 좋을 것 같습니다.
저는 아직 six, future 패키지 사용을 해보질 못해서 공부를 좀 해야 할 것 같네요.
괜찮으시다면 지원 작업을 부탁드려도 될까요? :)

Wow, If KicomAV supports Python 2.7, 3.5, and 3.6, it would be nice.
Can you help me?

**Comment by jaepil** [comment]
네 틈틈이 작업 시작하겠습니다. :)
