### ISSUE TITLE
elf파일에 대하여 --verbose 했을 경우 결과가 안나오는 문제

### ISSUE THREAD

**Issue by researcherGeekLab** [hanul93/kicomav#8]
![20171121_220616](https://user-images.githubusercontent.com/19469996/33074125-631c6ff0-cf08-11e7-8129-e906351d043c.png)

위 사진과 같이 elf파일은 파일에 대한 주요정보를 안 뽑아줍니다.

**Comment by hanul93** [comment]
문제라기 보다는 해당 기능이 존재하지 않아서 그렇습니다.
기능 추가가 필요한 부분이지요 :)
해당 기능을 추가하도록 하겠습니다.

**Comment by hanul93** [comment]
앗.. 제가 착각했네요. 해당 기능이 있네요.
확인해보도록 하겠습니다.

**Comment by hanul93** [comment]
혹시 해당 파일이 elf가 아닌건 아닐까요?
혹시 모르니 해당 파일을 메일로 보내주시겠습니까?

**Comment by researcherGeekLab** [comment]
메일 확인 부탁드립니다!

**Comment by hanul93** [comment]
파일을 확인했는데.. ELF 64bit네요.
ELF 32bit만 verbose 기능이 있고 ELF 64bit에는 기능이 없었네요.
verbose 기능을 추가하도록 하겠습니다.

**Comment by hanul93** [comment]
해당 기능을 추가했습니다.

![elf64_verbose](https://user-images.githubusercontent.com/4372914/33108786-5343d73e-cf81-11e7-9849-720c1cf4969e.png)

**Comment by hanul93** [comment]
관련 수정 내용은 다음에서 확인하실 수 있습니다.

https://github.com/hanul93/kicomav/commit/0d85113b5be70e8feefb9e26e5897f6764f9b642
